// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6YCqX3L7UTVG8PvKmpJ1lzxfgr3_Mvrs',
    appId: '1:1072532306463:web:be94f81206878ab9afb32a',
    messagingSenderId: '1072532306463',
    projectId: 'flutter-backend-5e26d',
    authDomain: 'flutter-backend-5e26d.firebaseapp.com',
    storageBucket: 'flutter-backend-5e26d.firebasestorage.app',
    measurementId: 'G-9T0VBYHG8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2dX-E_OkOzfdw9diErrbghF8PBP1MMjc',
    appId: '1:1072532306463:android:fa9ac07868b05e2bafb32a',
    messagingSenderId: '1072532306463',
    projectId: 'flutter-backend-5e26d',
    storageBucket: 'flutter-backend-5e26d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5gxBHBOHAk7OANXGRlrUfMOoTsqwKYdM',
    appId: '1:1072532306463:ios:de2f0c7fde1085eeafb32a',
    messagingSenderId: '1072532306463',
    projectId: 'flutter-backend-5e26d',
    storageBucket: 'flutter-backend-5e26d.firebasestorage.app',
    iosBundleId: 'com.example.moneymangementapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5gxBHBOHAk7OANXGRlrUfMOoTsqwKYdM',
    appId: '1:1072532306463:ios:de2f0c7fde1085eeafb32a',
    messagingSenderId: '1072532306463',
    projectId: 'flutter-backend-5e26d',
    storageBucket: 'flutter-backend-5e26d.firebasestorage.app',
    iosBundleId: 'com.example.moneymangementapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6YCqX3L7UTVG8PvKmpJ1lzxfgr3_Mvrs',
    appId: '1:1072532306463:web:8abb030e3e33b6f1afb32a',
    messagingSenderId: '1072532306463',
    projectId: 'flutter-backend-5e26d',
    authDomain: 'flutter-backend-5e26d.firebaseapp.com',
    storageBucket: 'flutter-backend-5e26d.firebasestorage.app',
    measurementId: 'G-42CDV1VZPG',
  );
}
